######  과제      
- 각 지하철 역별 평균 이용객 수         
- 각 지하철 역별 이용객 수 의 표준편차         
- 가장 많은 이용객이 있는 역의 이용객 수         
- 이용객 수가 가장 많은 역의 이름         
- 이용객 수가 가장 적은 역의 이름     
- 이용객 수의 분포를 히스토그램으로 시각화하기

In [104]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [105]:
file = './subway.csv'
data = pd.read_csv(file, encoding='cp949', usecols = (2,3,4))
data.head()

         역명  승차총승객수  하차총승객수
0  4.19민주묘지    1964    1773
1        가능    3917    3600
2      가락시장    3306    4148
3      가락시장    3871    4054
4   가산디지털단지    5219    7054

In [106]:
data['총이용객수'] = data['승차총승객수'] + data['하차총승객수']
data

            역명  승차총승객수  하차총승객수  총이용객수
0     4.19민주묘지    1964    1773   3737
1           가능    3917    3600   7517
2         가락시장    3306    4148   7454
3         가락시장    3871    4054   7925
4      가산디지털단지    5219    7054  12273
..         ...     ...     ...    ...
608         회룡    7555    7235  14790
609  회현(남대문시장)   11719   12414  24133
610      효창공원앞    1161    1565   2726
611      효창공원앞    3131    2862   5993
612  흑석(중앙대입구)    3639    4088   7727

[613 rows x 4 columns]

In [107]:
station = data['역명']
station.head()

0    4.19민주묘지
1          가능
2        가락시장
3        가락시장
4     가산디지털단지
Name: 역명, dtype: object

In [108]:
result = station.value_counts()
result.head()

역명
서울역               5
공덕                4
김포공항              4
디지털미디어시티          3
동대문역사문화공원(DDP)    3
Name: count, dtype: int64

In [109]:
result.index

Index(['서울역', '공덕', '김포공항', '디지털미디어시티', '동대문역사문화공원(DDP)', '신설동', '종로3가',
       '고속터미널', '왕십리(성동구청)', '홍대입구',
       ...
       '방학', '방이', '방배', '발산', '반포', '반월', '미아사거리', '미아(서울사이버대학)', '미사',
       '흑석(중앙대입구)'],
      dtype='object', name='역명', length=526)

In [110]:
station_list = result.index
station_list[:10]

Index(['서울역', '공덕', '김포공항', '디지털미디어시티', '동대문역사문화공원(DDP)', '신설동', '종로3가',
       '고속터미널', '왕십리(성동구청)', '홍대입구'],
      dtype='object', name='역명')

In [111]:
count_dict = {}

for i in range(data.shape[0]):
    #print(data.iloc[i][0], data.iloc[i][3])
    station = data.iloc[i][0]
    people = data.iloc[i][3]
    #print(station)
    #print(people)
    
    if station not in count_dict.keys():
        count_dict[station] = people
        
    else:
        count_dict[station] = count_dict[station] + people

In [112]:
count_dict

{'4.19민주묘지': 3737,
 '가능': 7517,
 '가락시장': 15379,
 '가산디지털단지': 32684,
 '가양': 20046,
 '가오리': 4479,
 '가좌': 5894,
 '가천대': 6548,
 '가평': 3255,
 '간석': 6659,
 '갈매': 2680,
 '강남': 61040,
 '강남구청': 13907,
 '강동': 16659,
 '강동구청': 9188,
 '강매': 3018,
 '강변(동서울터미널)': 45164,
 '강일': 5741,
 '강촌': 874,
 '개롱': 5806,
 '개봉': 23465,
 '개포동': 4175,
 '개화': 2083,
 '개화산': 6021,
 '거여': 8612,
 '건대입구': 66879,
 '검암': 7264,
 '경기광주': 8831,
 '경마공원': 957,
 '경복궁(정부서울청사)': 35556,
 '경찰병원': 6128,
 '계양': 13189,
 '고덕': 9529,
 '고려대(종암)': 6956,
 '고색': 4269,
 '고속터미널': 152970,
 '고잔': 8555,
 '곡산': 747,
 '곤지암': 3819,
 '공덕': 31692,
 '공릉(서울과학기술대)': 12311,
 '공항시장': 3455,
 '공항화물청사': 1953,
 '과천': 7014,
 '관악': 9623,
 '관악산(서울대)': 5549,
 '광나루(장신대)': 13742,
 '광명': 5845,
 '광명사거리': 22116,
 '광운대': 8429,
 '광화문(세종문화회관)': 30172,
 '광흥창(서강)': 6898,
 '교대(법원.검찰청)': 27748,
 '구로': 19636,
 '구로디지털단지': 47425,
 '구룡': 2539,
 '구리': 15470,
 '구반포': 674,
 '구산': 7215,
 '구성': 5232,
 '구의(광진구청)': 22600,
 '구일': 6208,
 '구파발': 24874,
 '국수': 949,
 '국회의사당': 5727,
 '군자(능동)': 26802,
 '군포': 6226,
 '굴봉산': 261,
 '굽은다리(강동구민회관앞)': 10959,
 '금곡': 1612,
 '금릉': 6648,
 '금정': 30936,
 '금천구청': 12371,
 '금촌': 9471,
 '금호': 8353,
 '기흥': 10151,
 '길동': 8674,
 '길음': 20581,
 '김유정': 750,
 '김포공항': 52751,
 '까치산': 29781,
 '낙성대(강감찬)': 27462,
 '남구로': 13121,
 '남동인더스파크': 1139,
 '남부터미널(예술의전당)': 33102,
 '남성': 11014,
 '남영': 8089,
 '남위례': 6600,
 '남춘천': 5775,
 '남태령': 1342,
 '남한산성입구(성남법원.검찰청)': 12309,
 '내방': 10024,
 '노들': 4328,
 '노량진': 40290,
 '노원': 67060,
 '녹번': 13754,
 '녹사평(용산구청)': 6319,
 '녹양': 5225,
 '녹천': 4023,
 '논현': 12417,
 '능곡': 5274,
 '단대오거리': 11934,
 '달월': 140,
 '답십리': 13665,
 '당고개': 11158,
 '당곡': 4883,
 '당산': 33373,
 '당정': 6192,
 '대곡': 2605,
 '대공원': 10449,
 '대림(구로구청)': 47948,
 '대모산입구': 5087,
 '대방': 12059,
 '대성리': 823,
 '대야미': 5782,
 '대청': 9183,
 '대치': 11396,
 '대화': 11477,
 '대흥(서강대앞)': 7161,
 '덕계': 5835,
 '덕소': 6760,
 '덕정': 7259,
 '도곡': 10605,
 '도농': 10858,
 '도림천': 1187,
 '도봉': 6460,
 '도봉산': 25062,
 '도심': 2285,
 '도원': 3645,
 '도화': 4621,
 '독립문': 9418,
 '독바위': 3160,
 '독산': 12576,
 '돌곶이': 11272,
 '동대문': 34714,
 '동대문역사문화공원(DDP)': 43174,
 '동대입구': 14361,
 '동두천': 2229,
 '동두천중앙': 4064,
 '동묘앞': 37172,
 '동암': 19677,
 '동인천': 18259,
 '동작(현충원)': 5167,
 '두정': 10652,
 '둔촌동': 8351,
 '둔촌오륜': 891,
 '등촌': 10430,
 '디지털미디어시티': 22741,
 '뚝섬': 20838,
 '뚝섬유원지': 11950,
 '마곡': 8094,
 '마곡나루(서울식물원)': 19531,
 '마두': 7540,
 '마들': 12327,
 '마석': 4734,
 '마장': 5385,
 '마천': 7097,
 '마포': 11074,
 '마포구청': 12227,
 '망우': 9220,
 '망원': 19012,
 '망월사': 8385,
 '망포': 14288,
 '매교': 4988,
 '매봉': 8258,
 '매탄권선': 5564,
 '먹골': 10477,
 '면목': 15023,
 '명동': 49462,
 '명일': 8820,
 '명학': 6202,
 '모란': 27174,
 '목동': 14780,
 '몽촌토성(평화의문)': 6384,
 '무악재': 4437,
 '문래': 15260,
 '문산': 7624,
 '문정': 9948,
 '미금': 15196,
 '미사': 20049,
 '미아(서울사이버대학)': 15129,
 '미아사거리': 31739,
 '반월': 5070,
 '반포': 6288,
 '발산': 19846,
 '방배': 10831,
 '방이': 6682,
 '방학': 11656,
 '방화': 7395,
 '배방': 2093,
 '백마': 7349,
 '백석': 11794,
 '백양리': 845,
 '백운': 8422,
 '버티고개': 2132,
 '범계': 30951,
 '별내': 3434,
 '병점': 22216,
 '보라매': 9673,
 '보라매공원': 2119,
 '보라매병원': 4510,
 '보문': 9401,
 '보산': 2696,
 '보정': 2492,
 '복정': 7029,
 '봉명': 1641,
 '봉은사': 19310,
 '봉천': 23478,
 '봉화산(서울의료원)': 7759,
 '부개': 9457,
 '부발': 3530,
 '부천': 45512,
 '부천종합운동장': 2067,
 '부평': 48056,
 '북한산보국문': 6934,
 '북한산우이': 6620,
 '불광': 27481,
 '사가정': 16894,
 '사당': 71964,
 '사릉': 2379,
 '사리': 5821,
 '사평': 3435,
 '산본': 19960,
 '산성': 6797,
 '삼각지': 13423,
 '삼동': 2326,
 '삼성(무역센터)': 37135,
 '삼성중앙': 4182,
 '삼송': 23198,
 '삼양': 2346,
 '삼양사거리': 3082,
 '삼전': 7481,
 '상갈': 6068,
 '상계': 20728,
 '상도': 9905,
 '상록수': 18001,
 '상봉': 26850,
 '상수': 13256,
 '상왕십리': 13458,
 '상월곡(한국과학기술연구원)': 5619,
 '상일동': 13091,
 '상천': 387,
 '새절(신사)': 12538,
 '샛강': 5867,
 '서강대': 2216,
 '서대문': 9916,
 '서동탄': 2129,
 '서빙고': 1812,
 '서울대벤처타운': 10788,
 '서울대입구(관악구청)': 46842,
 '서울숲': 12119,
 '서울역': 128280,
 '서울지방병무청': 3016,
 '서원': 3674,
 '서정리': 13446,
 '서초': 10106,
 '서현': 27805,
 '석계': 22638,
 '석수': 9243,
 '석촌': 18971,
 '석촌고분': 6766,
 '선릉': 30957,
 '선바위': 6137,
 '선유도': 5712,
 '선정릉': 9076,
 '성균관대': 17900,
 '성수': 40847,
 '성신여대입구(돈암)': 29817,
 '성환': 6352,
 '세류': 5169,
 '세마': 4090,
 '세종대왕릉': 620,
 '소래포구': 7848,
 '소사': 9150,
 '소요산': 4856,
 '솔밭공원': 2916,
 '솔샘': 5657,
 '송내': 24953,
 '송도': 3140,
 '송정': 7035,
 '송탄': 8294,
 '송파': 8857,
 '송파나루': 6064,
 '수내': 11736,
 '수락산': 14762,
 '수리산': 3902,
 '수색': 2534,
 '수서': 38754,
 '수원': 92979,
 '수원시청': 14856,
 '수유(강북구청)': 39914,
 '수진': 5408,
 '숙대입구(갈월)': 11843,
 '숭실대입구(살피재)': 11545,
 '숭의': 4272,
 '시청': 38492,
 '신갈': 4067,
 '신금호': 6091,
 '신길': 12441,
 '신길온천': 2681,
 '신내': 2193,
 '신논현': 31105,
 '신답': 1548,
 '신당': 26160,
 '신대방': 28571,
 '신대방삼거리': 14211,
 '신도림': 54927,
 '신둔도예촌': 1952,
 '신림': 64320,
 '신목동': 3414,
 '신반포': 3315,
 '신방화': 6990,
 '신사': 23603,
 '신설동': 20579,
 '신용산': 22005,
 '신원': 239,
 '신이문': 8801,
 '신정(은행정)': 11905,
 '신정네거리': 10620,
 '신창(순천향대)': 1949,
 '신촌': 41497,
 '신포': 2375,
 '신풍': 10285,
 '신흥': 6296,
 '쌍문': 29921,
 '쌍용(나사렛대)': 3098,
 '아산': 6766,
 '아신': 877,
 '아차산(어린이대공원후문)': 19171,
 '아현': 9867,
 '안국': 32646,
 '안산': 20653,
 '안암(고대병원앞)': 8652,
 '안양': 26675,
 '암사': 17091,
 '압구정': 28212,
 '압구정로데오': 18676,
 '애오개': 5003,
 '야당': 11817,
 '야목': 409,
 '야탑': 26539,
 '약수': 16913,
 '양수': 3098,
 '양원': 2791,
 '양재(서초구청)': 24616,
 '양정': 520,
 '양주': 9462,
 '양천구청': 6766,
 '양천향교': 8541,
 '양평': 9902,
 '어린이대공원(세종대)': 13258,
 '어천': 2073,
 '언주': 5602,
 '여의나루': 15862,
 '여의도': 37535,
 '여주': 4997,
 '역곡': 28364,
 '역삼': 20537,
 '역촌': 4293,
 '연수': 6129,
 '연신내': 39224,
 '연천': 3885,
 '염창': 16886,
 '영등포': 71256,
 '영등포구청': 19220,
 '영등포시장': 11074,
 '영종': 5637,
 '영통': 9873,
 '오금': 7555,
 '오류동': 12901,
 '오리': 10012,
 '오목교(목동운동장앞)': 22770,
 '오목천': 3952,
 '오빈': 360,
 '오산': 18543,
 '오산대': 4927,
 '오이도': 11860,
 '옥수': 10463,
 '온수(성공회대입구)': 14052,
 '온양온천': 10302,
 '올림픽공원(한국체대)': 10531,
 '왕십리(성동구청)': 42154,
 '외대앞': 8691,
 '용답': 3070,
 '용두(동대문구청)': 2187,
 '용마산(용마폭포공원)': 6423,
 '용문': 3445,
 '용산': 77413,
 '우장산': 13882,
 '운길산': 1508,
 '운서': 14330,
 '운정': 8136,
 '운천': 13,
 '원당': 12326,
 '원덕': 628,
 '원인재': 5631,
 '원종': 5792,
 '원흥': 11528,
 '월계': 7070,
 '월곡(동덕여대)': 10321,
 '월곶': 3382,
 '월드컵경기장(성산)': 7773,
 '월롱': 2053,
 '을지로3가': 25917,
 '을지로4가': 13364,
 '을지로입구': 46631,
 '응봉': 2317,
 '응암': 18636,
 '의왕': 9030,
 '의정부': 28554,
 '이대': 15509,
 '이매': 6821,
 '이수': 15668,
 '이천': 5220,
 '이촌(국립중앙박물관)': 16609,
 '이태원': 17269,
 '인덕원': 22139,
 '인천': 11322,
 '인천공항1터미널': 25972,
 '인천공항2터미널': 11535,
 '인천논현': 6474,
 '인하대': 6518,
 '일산': 11185,
 '일원': 7721,
 '임진강': 125,
 '잠실(송파구청)': 128526,
 '잠실나루': 10585,
 '잠실새내': 23949,
 '잠원': 4465,
 '장승배기': 8419,
 '장암': 2008,
 '장지': 18343,
 '장한평': 15432,
 '전곡': 2311,
 '정릉': 5151,
 '정발산': 9109,
 '정부과천청사': 8848,
 '정왕': 12726,
 '정자': 14742,
 '제기동': 19460,
 '제물포': 10431,
 '종각': 30099,
 '종로3가': 70523,
 '종로5가': 26109,
 '종합운동장': 10794,
 '주안': 22828,
 '주엽': 10407,
 '죽전': 16604,
 '중계': 12577,
 '중곡': 9987,
 '중동': 10139,
 '중랑': 6409,
 '중앙': 25457,
 '중앙보훈병원': 7673,
 '중화': 10196,
 '증미': 4963,
 '증산(명지대앞)': 10856,
 '지축': 6836,
 '지평': 87,
 '지행': 9300,
 '직산': 1446,
 '진위': 1931,
 '창동': 29737,
 '창신': 3001,
 '천마산': 1945,
 '천안': 13873,
 '천왕': 9548,
 '천호(풍납토성)': 42474,
 '철산': 20131,
 '청구': 6756,
 '청담': 11010,
 '청라국제도시': 7804,
 '청량리(서울시립대입구)': 58078,
 '청명': 4361,
 '청산': 211,
 '청평': 2878,
 '초월': 3699,
 '초지': 5508,
 '총신대입구(이수)': 21036,
 '춘천': 3115,
 '충무로': 22553,
 '충정로(경기대입구)': 8989,
 '탄현': 8405,
 '탕정': 2221,
 '태릉입구': 16164,
 '태평': 15318,
 '퇴계원': 3716,
 '파주': 1473,
 '판교': 7004,
 '팔당': 2196,
 '평내호평': 6794,
 '평촌': 12779,
 '평택': 27190,
 '평택지제': 7195,
 '풍산': 7151,
 '하계': 17089,
 '하남검단산': 10361,
 '하남시청(덕풍?신장)': 9153,
 '하남풍산': 4422,
 '학동': 9466,
 '학여울': 1411,
 '한강진': 12259,
 '한국항공대': 1651,
 '한남': 3951,
 '한대앞': 10201,
 '한성대입구(삼선교)': 14505,
 '한성백제': 2673,
 '한양대': 4871,
 '한티': 15209,
 '합정': 55171,
 '행당': 7110,
 '행신': 9543,
 '혜화': 45560,
 '호구포': 3611,
 '홍대입구': 153141,
 '홍제': 19099,
 '화계': 4062,
 '화곡': 27700,
 '화랑대(서울여대입구)': 9117,
 '화서': 36784,
 '화정': 19577,
 '회기': 26217,
 '회룡': 14790,
 '회현(남대문시장)': 24133,
 '효창공원앞': 8719,
 '흑석(중앙대입구)': 7727}

In [113]:
subway = []
for k, v in count_dict.items():
    result = []
    result.append(k)
    result.append(v)
    subway.append(result)
    
#subway

In [114]:
subway_df = pd.DataFrame(subway)
subway_df.columns = ['station', 'people']
subway_df

       station  people
0     4.19민주묘지    3737
1           가능    7517
2         가락시장   15379
3      가산디지털단지   32684
4           가양   20046
..         ...     ...
521         회기   26217
522         회룡   14790
523  회현(남대문시장)   24133
524      효창공원앞    8719
525  흑석(중앙대입구)    7727

[526 rows x 2 columns]

In [115]:
sub = subway_df.set_index(['station'])
sub

           people
station
4.19민주묘지     3737
가능           7517
가락시장        15379
가산디지털단지     32684
가양          20046
...           ...
회기          26217
회룡          14790
회현(남대문시장)   24133
효창공원앞        8719
흑석(중앙대입구)    7727

[526 rows x 1 columns]

In [116]:
#각 지하철 역별 평균 이용객 수
sub.mean()

people    14312.406844
dtype: float64

In [117]:
# 각 지하철 역별 이용객 수 의 표준편차
np.sqrt(sub)

               people
station
4.19민주묘지    61.131007
가능          86.700634
가락시장       124.012096
가산디지털단지    180.787168
가양         141.583897
...               ...
회기         161.916645
회룡         121.614144
회현(남대문시장)  155.347996
효창공원앞       93.375586
흑석(중앙대입구)   87.903356

[526 rows x 1 columns]

In [118]:
result = sub.sort_values(by='people')
result.tail()

# 가장 많은 이용객이 있는 역의 이용객 수      ====> '홍대입구'역에서 153,141명의 사람이 이용함
# 이용객 수가 가장 많은 역의 이름             ====> '홍대입구'역

          people
station
수원         92979
서울역       128280
잠실(송파구청)  128526
고속터미널     152970
홍대입구      153141

In [119]:
# 이용객 수가 가장 적은 역의 이름           ====> '운천'역
result.head()

         people
station
운천           13
지평           87
임진강         125
달월          140
청산          211

In [124]:
# 이용객 수의 분포를 히스토그램으로 시각화하기
fig = plt.figure(figsie = (10,6))
ax = fig.add_subplot(111)

graph = ax.hist(result, bins = 10, ranges = (0, 155000))
ax.set_xlabel('person')
ax.set_ylabel('station number')
plt.show()

AttributeError: Figure.set() got an unexpected keyword argument 'figsie'